version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - mysql_vol:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes: ["./:/var/www/html"]

  webserver:
    depends_on:
      - wordpress
    image: nginx
    container_name: webserver
    restart: always
    links:
      - phpfpm
    ports:
      - "80:80"
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/default:/etc/nginx/sites-enabled/default
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log
  
  phpfpm:
    image: php:fpm
    ports:
      - 9000:9000
    volumes:
      - ./public:/usr/share/nginx/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8183:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin

volumes:
  mysql_vol: {}
