version: '2'

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./mysql_data:/var/lib/mysql

    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./public/leaflab.us:/var/www/html
    #volumes: #["./:/var/www/html"]

  webserver:
    depends_on:
      - wordpress
    image: nginx
    container_name: webserver
    restart: always
    links:
      - phpfpm
    ports:
      - "80:80"
    #Mounts host dirs inside container (counters containerization)  
    volumes:
      - ./public/leaflab.us:/var/www/html:rw # With read/write privs
      - ./public/leaflab.us:/usr/share/nginx/html:rw # With read/write privs
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # With read-only privs
      #- ./nginx/default:/etc/nginx/sites-available/default
      #- ./nginx/default:/etc/nginx/sites-enabled/default
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log

  phpfpm:
    image: php:fpm
    ports:
      - 9000:9000
    volumes:
      - ./public/leaflab.us:/usr/share/nginx/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8183:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin

#volumes:
